version: '3.8'
services:
  kdence:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: 192.168.1.4
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_DB: kdence
